[tool.black]
line-length = 120

[tool.pylint]
max-line-length = 120
disable = [
    "invalid-name",
    "fixme",
    "missing-module-docstring",
    "missing-function-docstring",
    "missing-class-docstring",
]
